
-- 设置字符集
SET NAMES UTF8;

-- 表结构定义
CREATE TABLE "xxl_job_info" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                                "job_group" INT NOT NULL COMMENT '执行器主键ID',
                                "job_desc" VARCHAR(255) NOT NULL COMMENT '任务描述',
                                "add_time" TIMESTAMP DEFAULT NULL COMMENT '创建时间',
                                "update_time" TIMESTAMP DEFAULT NULL COMMENT '更新时间',
                                "author" VARCHAR(64) DEFAULT NULL COMMENT '作者',
                                "alarm_email" VARCHAR(255) DEFAULT NULL COMMENT '报警邮件',
                                "schedule_type" VARCHAR(50) NOT NULL DEFAULT 'NONE' COMMENT '调度类型',
                                "schedule_conf" VARCHAR(128) DEFAULT NULL COMMENT '调度配置',
                                "misfire_strategy" VARCHAR(50) NOT NULL DEFAULT 'DO_NOTHING' COMMENT '调度过期策略',
                                "executor_route_strategy" VARCHAR(50) DEFAULT NULL COMMENT '执行器路由策略',
                                "executor_handler" VARCHAR(255) DEFAULT NULL COMMENT '执行器任务handler',
                                "executor_param" VARCHAR(512) DEFAULT NULL COMMENT '执行器任务参数',
                                "executor_block_strategy" VARCHAR(50) DEFAULT NULL COMMENT '阻塞处理策略',
                                "executor_timeout" INT NOT NULL DEFAULT 0 COMMENT '任务执行超时时间(秒)',
                                "executor_fail_retry_count" INT NOT NULL DEFAULT 0 COMMENT '失败重试次数',
                                "glue_type" VARCHAR(50) NOT NULL COMMENT 'GLUE类型',
                                "glue_source" CLOB COMMENT 'GLUE源代码',
                                "glue_remark" VARCHAR(128) DEFAULT NULL COMMENT 'GLUE备注',
                                "glue_updatetime" TIMESTAMP DEFAULT NULL COMMENT 'GLUE更新时间',
                                "child_jobid" VARCHAR(255) DEFAULT NULL COMMENT '子任务ID',
                                "trigger_status" TINYINT NOT NULL DEFAULT 0 COMMENT '调度状态：0-停止，1-运行',
                                "trigger_last_time" BIGINT DEFAULT 0 COMMENT '上次调度时间',
                                "trigger_next_time" BIGINT DEFAULT 0 COMMENT '下次调度时间'
) COMMENT '任务信息表';

CREATE TABLE "xxl_job_log" (
                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                               "job_group" INT NOT NULL COMMENT '执行器主键ID',
                               "job_id" INT NOT NULL COMMENT '任务主键ID',
                               "executor_address" VARCHAR(255) DEFAULT NULL COMMENT '执行器地址',
                               "executor_handler" VARCHAR(255) DEFAULT NULL COMMENT '执行器任务handler',
                               "executor_param" VARCHAR(512) DEFAULT NULL COMMENT '执行器任务参数',
                               "executor_sharding_param" VARCHAR(20) DEFAULT NULL COMMENT '执行器任务分片参数',
                               "executor_fail_retry_count" INT NOT NULL DEFAULT 0 COMMENT '失败重试次数',
                               "trigger_time" TIMESTAMP DEFAULT NULL COMMENT '调度时间',
                               "trigger_code" INT NOT NULL COMMENT '调度结果',
                               "trigger_msg" CLOB COMMENT '调度日志',
                               "handle_time" TIMESTAMP DEFAULT NULL COMMENT '执行时间',
                               "handle_code" INT NOT NULL COMMENT '执行状态',
                               "handle_msg" CLOB COMMENT '执行日志',
                               "alarm_status" TINYINT NOT NULL DEFAULT 0 COMMENT '告警状态'
) COMMENT '任务执行日志表';

CREATE UNIQUE INDEX "I_trigger_time" ON "xxl_job_log"("trigger_time");
CREATE INDEX "I_handle_code" ON "xxl_job_log"("handle_code");

CREATE TABLE "xxl_job_log_report" (
                                      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                                      "trigger_day" TIMESTAMP DEFAULT NULL COMMENT '调度时间',
                                      "running_count" INT NOT NULL DEFAULT 0 COMMENT '运行中日志数量',
                                      "suc_count" INT NOT NULL DEFAULT 0 COMMENT '执行成功日志数量',
                                      "fail_count" INT NOT NULL DEFAULT 0 COMMENT '执行失败日志数量',
                                      "update_time" TIMESTAMP DEFAULT NULL COMMENT '更新时间'
) COMMENT '日志统计报表表';

CREATE UNIQUE INDEX "i_trigger_day" ON "xxl_job_log_report"("trigger_day");

CREATE TABLE "xxl_job_logglue" (
                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                                   "job_id" INT NOT NULL COMMENT '任务主键ID',
                                   "glue_type" VARCHAR(50) DEFAULT NULL COMMENT 'GLUE类型',
                                   "glue_source" CLOB COMMENT 'GLUE源代码',
                                   "glue_remark" VARCHAR(128) DEFAULT NULL COMMENT 'GLUE备注',
                                   "add_time" TIMESTAMP DEFAULT NULL COMMENT '添加时间',
                                   "update_time" TIMESTAMP DEFAULT NULL COMMENT '更新时间'
) COMMENT 'GLUE日志表';

CREATE TABLE "xxl_job_registry" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                                    "registry_group" VARCHAR(50) NOT NULL COMMENT '注册组',
                                    "registry_key" VARCHAR(255) NOT NULL COMMENT '注册键',
                                    "registry_value" VARCHAR(255) NOT NULL COMMENT '注册值',
                                    "update_time" TIMESTAMP DEFAULT NULL COMMENT '更新时间'
) COMMENT '注册中心表';

CREATE INDEX "i_g_k_v" ON "xxl_job_registry"("registry_group", "registry_key", "registry_value");

CREATE TABLE "xxl_job_group" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                                 "app_name" VARCHAR(64) NOT NULL COMMENT '执行器AppName',
                                 "title" VARCHAR(12) NOT NULL COMMENT '执行器名称',
                                 "address_type" TINYINT NOT NULL DEFAULT 0 COMMENT '地址类型：0=自动注册、1=手动录入',
                                 "address_list" VARCHAR(512) DEFAULT NULL COMMENT '执行器地址列表',
                                 "update_time" TIMESTAMP DEFAULT NULL COMMENT '更新时间'
) COMMENT '执行器组表';

INSERT INTO "xxl_job_group"("id", "app_name", "title", "address_type", "address_list", "update_time")
VALUES (1, 'xxl-job-executor-sample', '示例执行器', 0, NULL, '2018-11-03 22:21:31');

CREATE TABLE "xxl_job_user" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '主键ID',
                                "username" VARCHAR(50) NOT NULL COMMENT '账号',
                                "password" VARCHAR(50) NOT NULL COMMENT '密码',
                                "role" TINYINT NOT NULL DEFAULT 0 COMMENT '角色：0-普通用户、1-管理员',
                                "permission" VARCHAR(255) DEFAULT NULL COMMENT '权限：执行器ID列表'
) COMMENT '用户表';

INSERT INTO "xxl_job_user"("id", "username", "password", "role", "permission")
VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);

CREATE TABLE "xxl_job_lock" (
                                "lock_name" VARCHAR(50) PRIMARY KEY COMMENT '锁名称'
) COMMENT '分布式锁表';

INSERT INTO "xxl_job_lock"("lock_name") VALUES ('schedule_lock');

COMMIT;
